### ISSUE TITLE
Latest updates killed navbar and footer in pages not blog

### ISSUE THREAD

**Issue by donaldboulton** [v4iv/gatsby-starter-business#26] opened 2019-03-28 01:07 UTC
Investigating why after the latest changes my nav and footer are missing from Home Page,  Pricing Page, Contact Page. About page and Blog with Post pages is fine??
Revert to old in my repo.
Got this build error
  Please create layout component in that location or specify path to layout component in gatsby-config.js

**Comment by v4iv** [comment] 2019-03-28 02:06
Was previously using legacy layout wrapping system which was deprecated in gatsby 2, with the help of gatsby-plugin-layout.
I removed that and moved to component based wrapper as per Gatsby 2 specification, please check your code and make sure to wrap every page with Layout component.

**Comment by v4iv** [comment] 2019-03-28 11:32
I'll be closing this now since it's not a bug

**Closed by v4iv** 2019-03-28 11:32 UTC
